model: ScaleShiftMACE
num_channels: 32
max_L: 0
r_max: 4.0
name: model_scaleshift_lr0.0001_weighted01_25epochs_25batch
train_file: train_01.xyz
valid_fraction: 0.01
test_file: test_01.xyz
energy_key: REF_energy
forces_key: REF_forces
batch_size: 25
max_num_epochs: 25
optimizer: adam
lr: 0.0001
device: cpu
seed: 123
config_type_weights:
  highE: 0.1
  lowE: 0.05
